development:
  adapter: postgresql
  database: yakut_development
  username: postgres
  password: qwert
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432